services:
  node:
    container_name: angular-ngrx-frontend
    hostname: node
    build:
      context: .
      dockerfile: ./Dockerfile
      target: development
    command: sh -c 'if [ -z $PROD_MODE ]; then make start-yarn; else make start-yarn-prod; fi'
    user: $HOST_UID:$HOST_GID
    ports:
      - "4200:4200"
    volumes:
      - ./:/app:cached
