# Fetch used node image
FROM node:19.0.0

# Let's use bash as a default shell with login each time
SHELL ["/bin/bash", "--login", "-c"]

# Update package list and install necessary libraries
RUN apt-get update \
    && apt-get install -y \
        bash-completion \
        fish \
        git \
        jq \
        locales \
        nano \
        python3-dev \
        python3-pip \
        python3-setuptools \
        sudo \
        unzip \
    && rm -rf /var/lib/apt/lists/*

# Set the locale
RUN sed -i '/en_US.UTF-8/s/^# //g' /etc/locale.gen \
    && locale-gen

ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
ENV LC_ALL en_US.UTF-8

WORKDIR /app

# Add source code to container
ADD . .

# Add necessary stuff to bash autocomplete
RUN echo 'source /usr/share/bash-completion/bash_completion' >> /etc/bash.bashrc \
    && curl https://raw.githubusercontent.com/dsifford/yarn-completion/master/yarn-completion.bash >> /etc/bash.bashrc \
    && printf '\nNG_COMMANDS="add build config doc e2e generate help lint new run serve test update version xi18n"\ncomplete -W "$NG_COMMANDS" ng\n' >> /etc/bash.bashrc

# Link `ng` command, set entrypoint with `x` mark and install `ncu` and `mversion` tools
RUN ln -s /app/node_modules/.bin/ng /usr/local/bin/ng \
    && chmod +x docker-entrypoint-dev.sh \
    && npm install -g npm-check-updates mversion

# Add node user to sudo group and set password to `node`
RUN usermod -a -G sudo node \
    && usermod -p $(perl -e 'print crypt($ARGV[0], "password")' 'node') node

USER node

RUN pip3 install thefuck --user --no-warn-script-location

RUN mkdir -p /home/node/.config/fish/completions \
    && mkdir -p /home/node/.config/fish/functions

RUN fish -c 'curl -sL git.io/fisher | source && fisher install jorgebucaran/fisher' \
    && fish -c 'fisher install jorgebucaran/nvm.fish'

COPY ./docker/fish /home/node/.config/fish/

# Add necessary stuff to bash autocomplete
ENV PATH "$PATH:/home/node/.local/bin"

RUN echo 'eval "$(thefuck --alias)"' >> /home/node/.bashrc

# Expose port 4200 outside
EXPOSE 4200

# Set custom entrypoint for dev container
ENTRYPOINT ["/app/docker-entrypoint-dev.sh"]
