export * from 'src/app/shared/interfaces/application-configuration-interface';
export * from 'src/app/shared/interfaces/environment.interface';
export * from 'src/app/shared/interfaces/error-message.interface';
export * from 'src/app/shared/interfaces/error-message-client.interface';
export * from 'src/app/shared/interfaces/error-message-server.interface';
export * from 'src/app/shared/interfaces/localization.interface';
export * from 'src/app/shared/interfaces/server-error.interface';
export * from 'src/app/shared/interfaces/server-error-debug.interface';
export * from 'src/app/shared/interfaces/version.interface';
